[test]
preload = ["./tests/env.ts", "./tests/setup.ts"]
coverageThreshold = 0.9
coveragePathIgnorePatterns = ["**/dist/**", "**/index.ts", "**/*.interface.ts", "tests/**", "src/classes/app-error-code.ts", "src/modules/datastore/schemas/**"]
