/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root';
import { Route as ShellRouteImport } from './routes/_shell';
import { Route as LoginRouteImport } from './routes/login';
import { Route as ShellIndexRouteImport } from './routes/_shell/index';
import { Route as ShellBrowseRouteImport } from './routes/_shell/browse';
import { Route as ShellDownloadsRouteImport } from './routes/_shell/downloads';
import { Route as ShellGenresRouteImport } from './routes/_shell/genres';
import { Route as ShellLibraryRouteImport } from './routes/_shell/library';
import { Route as ShellSettingsRouteImport } from './routes/_shell/settings';
import { Route as ShellNovelsSlugRouteImport } from './routes/_shell/novels.$slug';
import { Route as ReadSlugOrdinalRouteImport } from './routes/read.$slug.$ordinal';

const ShellRoute = ShellRouteImport.update({
  id: '/_shell',
  getParentRoute: () => rootRouteImport,
} as any);
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any);
const ShellIndexRoute = ShellIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ShellRoute,
} as any);
const ShellBrowseRoute = ShellBrowseRouteImport.update({
  id: '/browse',
  path: '/browse',
  getParentRoute: () => ShellRoute,
} as any);
const ShellDownloadsRoute = ShellDownloadsRouteImport.update({
  id: '/downloads',
  path: '/downloads',
  getParentRoute: () => ShellRoute,
} as any);
const ShellGenresRoute = ShellGenresRouteImport.update({
  id: '/genres',
  path: '/genres',
  getParentRoute: () => ShellRoute,
} as any);
const ShellLibraryRoute = ShellLibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => ShellRoute,
} as any);
const ShellSettingsRoute = ShellSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => ShellRoute,
} as any);
const ShellNovelsSlugRoute = ShellNovelsSlugRouteImport.update({
  id: '/novels/$slug',
  path: '/novels/$slug',
  getParentRoute: () => ShellRoute,
} as any);
const ReadSlugOrdinalRoute = ReadSlugOrdinalRouteImport.update({
  id: '/read/$slug/$ordinal',
  path: '/read/$slug/$ordinal',
  getParentRoute: () => rootRouteImport,
} as any);

export interface FileRoutesByFullPath {
  '/': typeof ShellIndexRoute;
  '/login': typeof LoginRoute;
  '/browse': typeof ShellBrowseRoute;
  '/downloads': typeof ShellDownloadsRoute;
  '/genres': typeof ShellGenresRoute;
  '/library': typeof ShellLibraryRoute;
  '/settings': typeof ShellSettingsRoute;
  '/novels/$slug': typeof ShellNovelsSlugRoute;
  '/read/$slug/$ordinal': typeof ReadSlugOrdinalRoute;
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute;
  '/browse': typeof ShellBrowseRoute;
  '/downloads': typeof ShellDownloadsRoute;
  '/genres': typeof ShellGenresRoute;
  '/library': typeof ShellLibraryRoute;
  '/settings': typeof ShellSettingsRoute;
  '/': typeof ShellIndexRoute;
  '/novels/$slug': typeof ShellNovelsSlugRoute;
  '/read/$slug/$ordinal': typeof ReadSlugOrdinalRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  '/_shell': typeof ShellRouteWithChildren;
  '/login': typeof LoginRoute;
  '/_shell/browse': typeof ShellBrowseRoute;
  '/_shell/downloads': typeof ShellDownloadsRoute;
  '/_shell/genres': typeof ShellGenresRoute;
  '/_shell/library': typeof ShellLibraryRoute;
  '/_shell/settings': typeof ShellSettingsRoute;
  '/_shell/': typeof ShellIndexRoute;
  '/_shell/novels/$slug': typeof ShellNovelsSlugRoute;
  '/read/$slug/$ordinal': typeof ReadSlugOrdinalRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths: '/' | '/login' | '/browse' | '/downloads' | '/genres' | '/library' | '/settings' | '/novels/$slug' | '/read/$slug/$ordinal';
  fileRoutesByTo: FileRoutesByTo;
  to: '/login' | '/browse' | '/downloads' | '/genres' | '/library' | '/settings' | '/' | '/novels/$slug' | '/read/$slug/$ordinal';
  id:
    | '__root__'
    | '/_shell'
    | '/login'
    | '/_shell/browse'
    | '/_shell/downloads'
    | '/_shell/genres'
    | '/_shell/library'
    | '/_shell/settings'
    | '/_shell/'
    | '/_shell/novels/$slug'
    | '/read/$slug/$ordinal';
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  ShellRoute: typeof ShellRouteWithChildren;
  LoginRoute: typeof LoginRoute;
  ReadSlugOrdinalRoute: typeof ReadSlugOrdinalRoute;
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_shell': {
      id: '/_shell';
      path: '';
      fullPath: '/';
      preLoaderRoute: typeof ShellRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/login': {
      id: '/login';
      path: '/login';
      fullPath: '/login';
      preLoaderRoute: typeof LoginRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/_shell/': {
      id: '/_shell/';
      path: '/';
      fullPath: '/';
      preLoaderRoute: typeof ShellIndexRouteImport;
      parentRoute: typeof ShellRoute;
    };
    '/_shell/browse': {
      id: '/_shell/browse';
      path: '/browse';
      fullPath: '/browse';
      preLoaderRoute: typeof ShellBrowseRouteImport;
      parentRoute: typeof ShellRoute;
    };
    '/_shell/downloads': {
      id: '/_shell/downloads';
      path: '/downloads';
      fullPath: '/downloads';
      preLoaderRoute: typeof ShellDownloadsRouteImport;
      parentRoute: typeof ShellRoute;
    };
    '/_shell/genres': {
      id: '/_shell/genres';
      path: '/genres';
      fullPath: '/genres';
      preLoaderRoute: typeof ShellGenresRouteImport;
      parentRoute: typeof ShellRoute;
    };
    '/_shell/library': {
      id: '/_shell/library';
      path: '/library';
      fullPath: '/library';
      preLoaderRoute: typeof ShellLibraryRouteImport;
      parentRoute: typeof ShellRoute;
    };
    '/_shell/settings': {
      id: '/_shell/settings';
      path: '/settings';
      fullPath: '/settings';
      preLoaderRoute: typeof ShellSettingsRouteImport;
      parentRoute: typeof ShellRoute;
    };
    '/_shell/novels/$slug': {
      id: '/_shell/novels/$slug';
      path: '/novels/$slug';
      fullPath: '/novels/$slug';
      preLoaderRoute: typeof ShellNovelsSlugRouteImport;
      parentRoute: typeof ShellRoute;
    };
    '/read/$slug/$ordinal': {
      id: '/read/$slug/$ordinal';
      path: '/read/$slug/$ordinal';
      fullPath: '/read/$slug/$ordinal';
      preLoaderRoute: typeof ReadSlugOrdinalRouteImport;
      parentRoute: typeof rootRouteImport;
    };
  }
}

interface ShellRouteChildren {
  ShellBrowseRoute: typeof ShellBrowseRoute;
  ShellDownloadsRoute: typeof ShellDownloadsRoute;
  ShellGenresRoute: typeof ShellGenresRoute;
  ShellLibraryRoute: typeof ShellLibraryRoute;
  ShellSettingsRoute: typeof ShellSettingsRoute;
  ShellIndexRoute: typeof ShellIndexRoute;
  ShellNovelsSlugRoute: typeof ShellNovelsSlugRoute;
}

const ShellRouteChildren: ShellRouteChildren = {
  ShellBrowseRoute: ShellBrowseRoute,
  ShellDownloadsRoute: ShellDownloadsRoute,
  ShellGenresRoute: ShellGenresRoute,
  ShellLibraryRoute: ShellLibraryRoute,
  ShellSettingsRoute: ShellSettingsRoute,
  ShellIndexRoute: ShellIndexRoute,
  ShellNovelsSlugRoute: ShellNovelsSlugRoute,
};

const ShellRouteWithChildren = ShellRoute._addFileChildren(ShellRouteChildren);

const rootRouteChildren: RootRouteChildren = {
  ShellRoute: ShellRouteWithChildren,
  LoginRoute: LoginRoute,
  ReadSlugOrdinalRoute: ReadSlugOrdinalRoute,
};
export const routeTree = rootRouteImport._addFileChildren(rootRouteChildren)._addFileTypes<FileRouteTypes>();

import type { getRouter } from './router.tsx';
import type { createStart } from '@tanstack/react-start';
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true;
    router: Awaited<ReturnType<typeof getRouter>>;
  }
}
