[test]
preload = ["reflect-metadata"]
coverageSkipTestFiles = true
coverageReporter = ["text", "lcov"]
coverageDir = "coverage"
coveragePathIgnorePatterns = [
  "examples/**",
  "**/index.ts",
  "**/*.interface.ts",
  "src/injector/module-ref.ts",
]
