/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as NovelsNovelIdRouteImport } from './routes/novels/$novelId'
import { Route as NovelsNovelIdIndexRouteImport } from './routes/novels/$novelId/index'
import { Route as NovelsNovelIdVolumesRouteImport } from './routes/novels/$novelId/volumes'
import { Route as NovelsNovelIdStoryBibleRouteImport } from './routes/novels/$novelId/story-bible'
import { Route as NovelsNovelIdSourceRouteImport } from './routes/novels/$novelId/source'
import { Route as NovelsNovelIdSettingsRouteImport } from './routes/novels/$novelId/settings'
import { Route as NovelsNovelIdRunsRouteImport } from './routes/novels/$novelId/runs'
import { Route as NovelsNovelIdReviewRouteImport } from './routes/novels/$novelId/review'
import { Route as NovelsNovelIdRebrandRouteImport } from './routes/novels/$novelId/rebrand'
import { Route as NovelsNovelIdProposalsRouteImport } from './routes/novels/$novelId/proposals'
import { Route as NovelsNovelIdOverviewRouteImport } from './routes/novels/$novelId/overview'
import { Route as NovelsNovelIdChatRouteImport } from './routes/novels/$novelId/chat'
import { Route as NovelsNovelIdChaptersRouteImport } from './routes/novels/$novelId/chapters'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const NovelsNovelIdRoute = NovelsNovelIdRouteImport.update({
  id: '/novels/$novelId',
  path: '/novels/$novelId',
  getParentRoute: () => rootRouteImport,
} as any)
const NovelsNovelIdIndexRoute = NovelsNovelIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => NovelsNovelIdRoute,
} as any)
const NovelsNovelIdVolumesRoute = NovelsNovelIdVolumesRouteImport.update({
  id: '/volumes',
  path: '/volumes',
  getParentRoute: () => NovelsNovelIdRoute,
} as any)
const NovelsNovelIdStoryBibleRoute = NovelsNovelIdStoryBibleRouteImport.update({
  id: '/story-bible',
  path: '/story-bible',
  getParentRoute: () => NovelsNovelIdRoute,
} as any)
const NovelsNovelIdSourceRoute = NovelsNovelIdSourceRouteImport.update({
  id: '/source',
  path: '/source',
  getParentRoute: () => NovelsNovelIdRoute,
} as any)
const NovelsNovelIdSettingsRoute = NovelsNovelIdSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => NovelsNovelIdRoute,
} as any)
const NovelsNovelIdRunsRoute = NovelsNovelIdRunsRouteImport.update({
  id: '/runs',
  path: '/runs',
  getParentRoute: () => NovelsNovelIdRoute,
} as any)
const NovelsNovelIdReviewRoute = NovelsNovelIdReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => NovelsNovelIdRoute,
} as any)
const NovelsNovelIdRebrandRoute = NovelsNovelIdRebrandRouteImport.update({
  id: '/rebrand',
  path: '/rebrand',
  getParentRoute: () => NovelsNovelIdRoute,
} as any)
const NovelsNovelIdProposalsRoute = NovelsNovelIdProposalsRouteImport.update({
  id: '/proposals',
  path: '/proposals',
  getParentRoute: () => NovelsNovelIdRoute,
} as any)
const NovelsNovelIdOverviewRoute = NovelsNovelIdOverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => NovelsNovelIdRoute,
} as any)
const NovelsNovelIdChatRoute = NovelsNovelIdChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => NovelsNovelIdRoute,
} as any)
const NovelsNovelIdChaptersRoute = NovelsNovelIdChaptersRouteImport.update({
  id: '/chapters',
  path: '/chapters',
  getParentRoute: () => NovelsNovelIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/novels/$novelId': typeof NovelsNovelIdRouteWithChildren
  '/novels/$novelId/chapters': typeof NovelsNovelIdChaptersRoute
  '/novels/$novelId/chat': typeof NovelsNovelIdChatRoute
  '/novels/$novelId/overview': typeof NovelsNovelIdOverviewRoute
  '/novels/$novelId/proposals': typeof NovelsNovelIdProposalsRoute
  '/novels/$novelId/rebrand': typeof NovelsNovelIdRebrandRoute
  '/novels/$novelId/review': typeof NovelsNovelIdReviewRoute
  '/novels/$novelId/runs': typeof NovelsNovelIdRunsRoute
  '/novels/$novelId/settings': typeof NovelsNovelIdSettingsRoute
  '/novels/$novelId/source': typeof NovelsNovelIdSourceRoute
  '/novels/$novelId/story-bible': typeof NovelsNovelIdStoryBibleRoute
  '/novels/$novelId/volumes': typeof NovelsNovelIdVolumesRoute
  '/novels/$novelId/': typeof NovelsNovelIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof AppIndexRoute
  '/novels/$novelId/chapters': typeof NovelsNovelIdChaptersRoute
  '/novels/$novelId/chat': typeof NovelsNovelIdChatRoute
  '/novels/$novelId/overview': typeof NovelsNovelIdOverviewRoute
  '/novels/$novelId/proposals': typeof NovelsNovelIdProposalsRoute
  '/novels/$novelId/rebrand': typeof NovelsNovelIdRebrandRoute
  '/novels/$novelId/review': typeof NovelsNovelIdReviewRoute
  '/novels/$novelId/runs': typeof NovelsNovelIdRunsRoute
  '/novels/$novelId/settings': typeof NovelsNovelIdSettingsRoute
  '/novels/$novelId/source': typeof NovelsNovelIdSourceRoute
  '/novels/$novelId/story-bible': typeof NovelsNovelIdStoryBibleRoute
  '/novels/$novelId/volumes': typeof NovelsNovelIdVolumesRoute
  '/novels/$novelId': typeof NovelsNovelIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/novels/$novelId': typeof NovelsNovelIdRouteWithChildren
  '/_app/': typeof AppIndexRoute
  '/novels/$novelId/chapters': typeof NovelsNovelIdChaptersRoute
  '/novels/$novelId/chat': typeof NovelsNovelIdChatRoute
  '/novels/$novelId/overview': typeof NovelsNovelIdOverviewRoute
  '/novels/$novelId/proposals': typeof NovelsNovelIdProposalsRoute
  '/novels/$novelId/rebrand': typeof NovelsNovelIdRebrandRoute
  '/novels/$novelId/review': typeof NovelsNovelIdReviewRoute
  '/novels/$novelId/runs': typeof NovelsNovelIdRunsRoute
  '/novels/$novelId/settings': typeof NovelsNovelIdSettingsRoute
  '/novels/$novelId/source': typeof NovelsNovelIdSourceRoute
  '/novels/$novelId/story-bible': typeof NovelsNovelIdStoryBibleRoute
  '/novels/$novelId/volumes': typeof NovelsNovelIdVolumesRoute
  '/novels/$novelId/': typeof NovelsNovelIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/novels/$novelId'
    | '/novels/$novelId/chapters'
    | '/novels/$novelId/chat'
    | '/novels/$novelId/overview'
    | '/novels/$novelId/proposals'
    | '/novels/$novelId/rebrand'
    | '/novels/$novelId/review'
    | '/novels/$novelId/runs'
    | '/novels/$novelId/settings'
    | '/novels/$novelId/source'
    | '/novels/$novelId/story-bible'
    | '/novels/$novelId/volumes'
    | '/novels/$novelId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/novels/$novelId/chapters'
    | '/novels/$novelId/chat'
    | '/novels/$novelId/overview'
    | '/novels/$novelId/proposals'
    | '/novels/$novelId/rebrand'
    | '/novels/$novelId/review'
    | '/novels/$novelId/runs'
    | '/novels/$novelId/settings'
    | '/novels/$novelId/source'
    | '/novels/$novelId/story-bible'
    | '/novels/$novelId/volumes'
    | '/novels/$novelId'
  id:
    | '__root__'
    | '/_app'
    | '/novels/$novelId'
    | '/_app/'
    | '/novels/$novelId/chapters'
    | '/novels/$novelId/chat'
    | '/novels/$novelId/overview'
    | '/novels/$novelId/proposals'
    | '/novels/$novelId/rebrand'
    | '/novels/$novelId/review'
    | '/novels/$novelId/runs'
    | '/novels/$novelId/settings'
    | '/novels/$novelId/source'
    | '/novels/$novelId/story-bible'
    | '/novels/$novelId/volumes'
    | '/novels/$novelId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  NovelsNovelIdRoute: typeof NovelsNovelIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/novels/$novelId': {
      id: '/novels/$novelId'
      path: '/novels/$novelId'
      fullPath: '/novels/$novelId'
      preLoaderRoute: typeof NovelsNovelIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/novels/$novelId/': {
      id: '/novels/$novelId/'
      path: '/'
      fullPath: '/novels/$novelId/'
      preLoaderRoute: typeof NovelsNovelIdIndexRouteImport
      parentRoute: typeof NovelsNovelIdRoute
    }
    '/novels/$novelId/volumes': {
      id: '/novels/$novelId/volumes'
      path: '/volumes'
      fullPath: '/novels/$novelId/volumes'
      preLoaderRoute: typeof NovelsNovelIdVolumesRouteImport
      parentRoute: typeof NovelsNovelIdRoute
    }
    '/novels/$novelId/story-bible': {
      id: '/novels/$novelId/story-bible'
      path: '/story-bible'
      fullPath: '/novels/$novelId/story-bible'
      preLoaderRoute: typeof NovelsNovelIdStoryBibleRouteImport
      parentRoute: typeof NovelsNovelIdRoute
    }
    '/novels/$novelId/source': {
      id: '/novels/$novelId/source'
      path: '/source'
      fullPath: '/novels/$novelId/source'
      preLoaderRoute: typeof NovelsNovelIdSourceRouteImport
      parentRoute: typeof NovelsNovelIdRoute
    }
    '/novels/$novelId/settings': {
      id: '/novels/$novelId/settings'
      path: '/settings'
      fullPath: '/novels/$novelId/settings'
      preLoaderRoute: typeof NovelsNovelIdSettingsRouteImport
      parentRoute: typeof NovelsNovelIdRoute
    }
    '/novels/$novelId/runs': {
      id: '/novels/$novelId/runs'
      path: '/runs'
      fullPath: '/novels/$novelId/runs'
      preLoaderRoute: typeof NovelsNovelIdRunsRouteImport
      parentRoute: typeof NovelsNovelIdRoute
    }
    '/novels/$novelId/review': {
      id: '/novels/$novelId/review'
      path: '/review'
      fullPath: '/novels/$novelId/review'
      preLoaderRoute: typeof NovelsNovelIdReviewRouteImport
      parentRoute: typeof NovelsNovelIdRoute
    }
    '/novels/$novelId/rebrand': {
      id: '/novels/$novelId/rebrand'
      path: '/rebrand'
      fullPath: '/novels/$novelId/rebrand'
      preLoaderRoute: typeof NovelsNovelIdRebrandRouteImport
      parentRoute: typeof NovelsNovelIdRoute
    }
    '/novels/$novelId/proposals': {
      id: '/novels/$novelId/proposals'
      path: '/proposals'
      fullPath: '/novels/$novelId/proposals'
      preLoaderRoute: typeof NovelsNovelIdProposalsRouteImport
      parentRoute: typeof NovelsNovelIdRoute
    }
    '/novels/$novelId/overview': {
      id: '/novels/$novelId/overview'
      path: '/overview'
      fullPath: '/novels/$novelId/overview'
      preLoaderRoute: typeof NovelsNovelIdOverviewRouteImport
      parentRoute: typeof NovelsNovelIdRoute
    }
    '/novels/$novelId/chat': {
      id: '/novels/$novelId/chat'
      path: '/chat'
      fullPath: '/novels/$novelId/chat'
      preLoaderRoute: typeof NovelsNovelIdChatRouteImport
      parentRoute: typeof NovelsNovelIdRoute
    }
    '/novels/$novelId/chapters': {
      id: '/novels/$novelId/chapters'
      path: '/chapters'
      fullPath: '/novels/$novelId/chapters'
      preLoaderRoute: typeof NovelsNovelIdChaptersRouteImport
      parentRoute: typeof NovelsNovelIdRoute
    }
  }
}

interface AppRouteChildren {
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface NovelsNovelIdRouteChildren {
  NovelsNovelIdChaptersRoute: typeof NovelsNovelIdChaptersRoute
  NovelsNovelIdChatRoute: typeof NovelsNovelIdChatRoute
  NovelsNovelIdOverviewRoute: typeof NovelsNovelIdOverviewRoute
  NovelsNovelIdProposalsRoute: typeof NovelsNovelIdProposalsRoute
  NovelsNovelIdRebrandRoute: typeof NovelsNovelIdRebrandRoute
  NovelsNovelIdReviewRoute: typeof NovelsNovelIdReviewRoute
  NovelsNovelIdRunsRoute: typeof NovelsNovelIdRunsRoute
  NovelsNovelIdSettingsRoute: typeof NovelsNovelIdSettingsRoute
  NovelsNovelIdSourceRoute: typeof NovelsNovelIdSourceRoute
  NovelsNovelIdStoryBibleRoute: typeof NovelsNovelIdStoryBibleRoute
  NovelsNovelIdVolumesRoute: typeof NovelsNovelIdVolumesRoute
  NovelsNovelIdIndexRoute: typeof NovelsNovelIdIndexRoute
}

const NovelsNovelIdRouteChildren: NovelsNovelIdRouteChildren = {
  NovelsNovelIdChaptersRoute: NovelsNovelIdChaptersRoute,
  NovelsNovelIdChatRoute: NovelsNovelIdChatRoute,
  NovelsNovelIdOverviewRoute: NovelsNovelIdOverviewRoute,
  NovelsNovelIdProposalsRoute: NovelsNovelIdProposalsRoute,
  NovelsNovelIdRebrandRoute: NovelsNovelIdRebrandRoute,
  NovelsNovelIdReviewRoute: NovelsNovelIdReviewRoute,
  NovelsNovelIdRunsRoute: NovelsNovelIdRunsRoute,
  NovelsNovelIdSettingsRoute: NovelsNovelIdSettingsRoute,
  NovelsNovelIdSourceRoute: NovelsNovelIdSourceRoute,
  NovelsNovelIdStoryBibleRoute: NovelsNovelIdStoryBibleRoute,
  NovelsNovelIdVolumesRoute: NovelsNovelIdVolumesRoute,
  NovelsNovelIdIndexRoute: NovelsNovelIdIndexRoute,
}

const NovelsNovelIdRouteWithChildren = NovelsNovelIdRoute._addFileChildren(
  NovelsNovelIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  NovelsNovelIdRoute: NovelsNovelIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
