/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as NovelsNovelIdRouteImport } from './routes/novels/$novelId'
import { Route as AppSitemapRouteImport } from './routes/_app/sitemap'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppProjectsRouteImport } from './routes/_app/projects'
import { Route as AppProfileRouteImport } from './routes/_app/profile'
import { Route as NovelsNovelIdIndexRouteImport } from './routes/novels/$novelId/index'
import { Route as NovelsNovelIdWorldRouteImport } from './routes/novels/$novelId/world'
import { Route as NovelsNovelIdVolumesRouteImport } from './routes/novels/$novelId/volumes'
import { Route as NovelsNovelIdVersionsRouteImport } from './routes/novels/$novelId/versions'
import { Route as NovelsNovelIdTimelineRouteImport } from './routes/novels/$novelId/timeline'
import { Route as NovelsNovelIdStoryBibleRouteImport } from './routes/novels/$novelId/story-bible'
import { Route as NovelsNovelIdSpeciesRouteImport } from './routes/novels/$novelId/species'
import { Route as NovelsNovelIdPlotRouteImport } from './routes/novels/$novelId/plot'
import { Route as NovelsNovelIdOverviewRouteImport } from './routes/novels/$novelId/overview'
import { Route as NovelsNovelIdMagicRouteImport } from './routes/novels/$novelId/magic'
import { Route as NovelsNovelIdLoreRouteImport } from './routes/novels/$novelId/lore'
import { Route as NovelsNovelIdLocationsRouteImport } from './routes/novels/$novelId/locations'
import { Route as NovelsNovelIdFactionsRouteImport } from './routes/novels/$novelId/factions'
import { Route as NovelsNovelIdContinuityRouteImport } from './routes/novels/$novelId/continuity'
import { Route as NovelsNovelIdCharactersRouteImport } from './routes/novels/$novelId/characters'
import { Route as NovelsNovelIdChaptersRouteImport } from './routes/novels/$novelId/chapters'
import { Route as NovelsNovelIdChapterReviewRouteImport } from './routes/novels/$novelId/chapter-review'
import { Route as NovelsNovelIdChapterGenerateRouteImport } from './routes/novels/$novelId/chapter-generate'
import { Route as NovelsNovelIdChapterEditorRouteImport } from './routes/novels/$novelId/chapter-editor'
import { Route as NovelsNovelIdChapterBriefRouteImport } from './routes/novels/$novelId/chapter-brief'
import { Route as NovelsNovelIdAssetsRouteImport } from './routes/novels/$novelId/assets'
import { Route as NovelsNovelIdApprovalsRouteImport } from './routes/novels/$novelId/approvals'
import { Route as NovelsNovelIdCharacterCharacterIdRouteImport } from './routes/novels/$novelId/character.$characterId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const NovelsNovelIdRoute = NovelsNovelIdRouteImport.update({
  id: '/novels/$novelId',
  path: '/novels/$novelId',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSitemapRoute = AppSitemapRouteImport.update({
  id: '/sitemap',
  path: '/sitemap',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectsRoute = AppProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const NovelsNovelIdIndexRoute = NovelsNovelIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => NovelsNovelIdRoute,
} as any)
const NovelsNovelIdWorldRoute = NovelsNovelIdWorldRouteImport.update({
  id: '/world',
  path: '/world',
  getParentRoute: () => NovelsNovelIdRoute,
} as any)
const NovelsNovelIdVolumesRoute = NovelsNovelIdVolumesRouteImport.update({
  id: '/volumes',
  path: '/volumes',
  getParentRoute: () => NovelsNovelIdRoute,
} as any)
const NovelsNovelIdVersionsRoute = NovelsNovelIdVersionsRouteImport.update({
  id: '/versions',
  path: '/versions',
  getParentRoute: () => NovelsNovelIdRoute,
} as any)
const NovelsNovelIdTimelineRoute = NovelsNovelIdTimelineRouteImport.update({
  id: '/timeline',
  path: '/timeline',
  getParentRoute: () => NovelsNovelIdRoute,
} as any)
const NovelsNovelIdStoryBibleRoute = NovelsNovelIdStoryBibleRouteImport.update({
  id: '/story-bible',
  path: '/story-bible',
  getParentRoute: () => NovelsNovelIdRoute,
} as any)
const NovelsNovelIdSpeciesRoute = NovelsNovelIdSpeciesRouteImport.update({
  id: '/species',
  path: '/species',
  getParentRoute: () => NovelsNovelIdRoute,
} as any)
const NovelsNovelIdPlotRoute = NovelsNovelIdPlotRouteImport.update({
  id: '/plot',
  path: '/plot',
  getParentRoute: () => NovelsNovelIdRoute,
} as any)
const NovelsNovelIdOverviewRoute = NovelsNovelIdOverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => NovelsNovelIdRoute,
} as any)
const NovelsNovelIdMagicRoute = NovelsNovelIdMagicRouteImport.update({
  id: '/magic',
  path: '/magic',
  getParentRoute: () => NovelsNovelIdRoute,
} as any)
const NovelsNovelIdLoreRoute = NovelsNovelIdLoreRouteImport.update({
  id: '/lore',
  path: '/lore',
  getParentRoute: () => NovelsNovelIdRoute,
} as any)
const NovelsNovelIdLocationsRoute = NovelsNovelIdLocationsRouteImport.update({
  id: '/locations',
  path: '/locations',
  getParentRoute: () => NovelsNovelIdRoute,
} as any)
const NovelsNovelIdFactionsRoute = NovelsNovelIdFactionsRouteImport.update({
  id: '/factions',
  path: '/factions',
  getParentRoute: () => NovelsNovelIdRoute,
} as any)
const NovelsNovelIdContinuityRoute = NovelsNovelIdContinuityRouteImport.update({
  id: '/continuity',
  path: '/continuity',
  getParentRoute: () => NovelsNovelIdRoute,
} as any)
const NovelsNovelIdCharactersRoute = NovelsNovelIdCharactersRouteImport.update({
  id: '/characters',
  path: '/characters',
  getParentRoute: () => NovelsNovelIdRoute,
} as any)
const NovelsNovelIdChaptersRoute = NovelsNovelIdChaptersRouteImport.update({
  id: '/chapters',
  path: '/chapters',
  getParentRoute: () => NovelsNovelIdRoute,
} as any)
const NovelsNovelIdChapterReviewRoute =
  NovelsNovelIdChapterReviewRouteImport.update({
    id: '/chapter-review',
    path: '/chapter-review',
    getParentRoute: () => NovelsNovelIdRoute,
  } as any)
const NovelsNovelIdChapterGenerateRoute =
  NovelsNovelIdChapterGenerateRouteImport.update({
    id: '/chapter-generate',
    path: '/chapter-generate',
    getParentRoute: () => NovelsNovelIdRoute,
  } as any)
const NovelsNovelIdChapterEditorRoute =
  NovelsNovelIdChapterEditorRouteImport.update({
    id: '/chapter-editor',
    path: '/chapter-editor',
    getParentRoute: () => NovelsNovelIdRoute,
  } as any)
const NovelsNovelIdChapterBriefRoute =
  NovelsNovelIdChapterBriefRouteImport.update({
    id: '/chapter-brief',
    path: '/chapter-brief',
    getParentRoute: () => NovelsNovelIdRoute,
  } as any)
const NovelsNovelIdAssetsRoute = NovelsNovelIdAssetsRouteImport.update({
  id: '/assets',
  path: '/assets',
  getParentRoute: () => NovelsNovelIdRoute,
} as any)
const NovelsNovelIdApprovalsRoute = NovelsNovelIdApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => NovelsNovelIdRoute,
} as any)
const NovelsNovelIdCharacterCharacterIdRoute =
  NovelsNovelIdCharacterCharacterIdRouteImport.update({
    id: '/character/$characterId',
    path: '/character/$characterId',
    getParentRoute: () => NovelsNovelIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/profile': typeof AppProfileRoute
  '/projects': typeof AppProjectsRoute
  '/settings': typeof AppSettingsRoute
  '/sitemap': typeof AppSitemapRoute
  '/novels/$novelId': typeof NovelsNovelIdRouteWithChildren
  '/novels/$novelId/approvals': typeof NovelsNovelIdApprovalsRoute
  '/novels/$novelId/assets': typeof NovelsNovelIdAssetsRoute
  '/novels/$novelId/chapter-brief': typeof NovelsNovelIdChapterBriefRoute
  '/novels/$novelId/chapter-editor': typeof NovelsNovelIdChapterEditorRoute
  '/novels/$novelId/chapter-generate': typeof NovelsNovelIdChapterGenerateRoute
  '/novels/$novelId/chapter-review': typeof NovelsNovelIdChapterReviewRoute
  '/novels/$novelId/chapters': typeof NovelsNovelIdChaptersRoute
  '/novels/$novelId/characters': typeof NovelsNovelIdCharactersRoute
  '/novels/$novelId/continuity': typeof NovelsNovelIdContinuityRoute
  '/novels/$novelId/factions': typeof NovelsNovelIdFactionsRoute
  '/novels/$novelId/locations': typeof NovelsNovelIdLocationsRoute
  '/novels/$novelId/lore': typeof NovelsNovelIdLoreRoute
  '/novels/$novelId/magic': typeof NovelsNovelIdMagicRoute
  '/novels/$novelId/overview': typeof NovelsNovelIdOverviewRoute
  '/novels/$novelId/plot': typeof NovelsNovelIdPlotRoute
  '/novels/$novelId/species': typeof NovelsNovelIdSpeciesRoute
  '/novels/$novelId/story-bible': typeof NovelsNovelIdStoryBibleRoute
  '/novels/$novelId/timeline': typeof NovelsNovelIdTimelineRoute
  '/novels/$novelId/versions': typeof NovelsNovelIdVersionsRoute
  '/novels/$novelId/volumes': typeof NovelsNovelIdVolumesRoute
  '/novels/$novelId/world': typeof NovelsNovelIdWorldRoute
  '/novels/$novelId/': typeof NovelsNovelIdIndexRoute
  '/novels/$novelId/character/$characterId': typeof NovelsNovelIdCharacterCharacterIdRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/profile': typeof AppProfileRoute
  '/projects': typeof AppProjectsRoute
  '/settings': typeof AppSettingsRoute
  '/sitemap': typeof AppSitemapRoute
  '/': typeof AppIndexRoute
  '/novels/$novelId/approvals': typeof NovelsNovelIdApprovalsRoute
  '/novels/$novelId/assets': typeof NovelsNovelIdAssetsRoute
  '/novels/$novelId/chapter-brief': typeof NovelsNovelIdChapterBriefRoute
  '/novels/$novelId/chapter-editor': typeof NovelsNovelIdChapterEditorRoute
  '/novels/$novelId/chapter-generate': typeof NovelsNovelIdChapterGenerateRoute
  '/novels/$novelId/chapter-review': typeof NovelsNovelIdChapterReviewRoute
  '/novels/$novelId/chapters': typeof NovelsNovelIdChaptersRoute
  '/novels/$novelId/characters': typeof NovelsNovelIdCharactersRoute
  '/novels/$novelId/continuity': typeof NovelsNovelIdContinuityRoute
  '/novels/$novelId/factions': typeof NovelsNovelIdFactionsRoute
  '/novels/$novelId/locations': typeof NovelsNovelIdLocationsRoute
  '/novels/$novelId/lore': typeof NovelsNovelIdLoreRoute
  '/novels/$novelId/magic': typeof NovelsNovelIdMagicRoute
  '/novels/$novelId/overview': typeof NovelsNovelIdOverviewRoute
  '/novels/$novelId/plot': typeof NovelsNovelIdPlotRoute
  '/novels/$novelId/species': typeof NovelsNovelIdSpeciesRoute
  '/novels/$novelId/story-bible': typeof NovelsNovelIdStoryBibleRoute
  '/novels/$novelId/timeline': typeof NovelsNovelIdTimelineRoute
  '/novels/$novelId/versions': typeof NovelsNovelIdVersionsRoute
  '/novels/$novelId/volumes': typeof NovelsNovelIdVolumesRoute
  '/novels/$novelId/world': typeof NovelsNovelIdWorldRoute
  '/novels/$novelId': typeof NovelsNovelIdIndexRoute
  '/novels/$novelId/character/$characterId': typeof NovelsNovelIdCharacterCharacterIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/profile': typeof AppProfileRoute
  '/_app/projects': typeof AppProjectsRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/sitemap': typeof AppSitemapRoute
  '/novels/$novelId': typeof NovelsNovelIdRouteWithChildren
  '/_app/': typeof AppIndexRoute
  '/novels/$novelId/approvals': typeof NovelsNovelIdApprovalsRoute
  '/novels/$novelId/assets': typeof NovelsNovelIdAssetsRoute
  '/novels/$novelId/chapter-brief': typeof NovelsNovelIdChapterBriefRoute
  '/novels/$novelId/chapter-editor': typeof NovelsNovelIdChapterEditorRoute
  '/novels/$novelId/chapter-generate': typeof NovelsNovelIdChapterGenerateRoute
  '/novels/$novelId/chapter-review': typeof NovelsNovelIdChapterReviewRoute
  '/novels/$novelId/chapters': typeof NovelsNovelIdChaptersRoute
  '/novels/$novelId/characters': typeof NovelsNovelIdCharactersRoute
  '/novels/$novelId/continuity': typeof NovelsNovelIdContinuityRoute
  '/novels/$novelId/factions': typeof NovelsNovelIdFactionsRoute
  '/novels/$novelId/locations': typeof NovelsNovelIdLocationsRoute
  '/novels/$novelId/lore': typeof NovelsNovelIdLoreRoute
  '/novels/$novelId/magic': typeof NovelsNovelIdMagicRoute
  '/novels/$novelId/overview': typeof NovelsNovelIdOverviewRoute
  '/novels/$novelId/plot': typeof NovelsNovelIdPlotRoute
  '/novels/$novelId/species': typeof NovelsNovelIdSpeciesRoute
  '/novels/$novelId/story-bible': typeof NovelsNovelIdStoryBibleRoute
  '/novels/$novelId/timeline': typeof NovelsNovelIdTimelineRoute
  '/novels/$novelId/versions': typeof NovelsNovelIdVersionsRoute
  '/novels/$novelId/volumes': typeof NovelsNovelIdVolumesRoute
  '/novels/$novelId/world': typeof NovelsNovelIdWorldRoute
  '/novels/$novelId/': typeof NovelsNovelIdIndexRoute
  '/novels/$novelId/character/$characterId': typeof NovelsNovelIdCharacterCharacterIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/profile'
    | '/projects'
    | '/settings'
    | '/sitemap'
    | '/novels/$novelId'
    | '/novels/$novelId/approvals'
    | '/novels/$novelId/assets'
    | '/novels/$novelId/chapter-brief'
    | '/novels/$novelId/chapter-editor'
    | '/novels/$novelId/chapter-generate'
    | '/novels/$novelId/chapter-review'
    | '/novels/$novelId/chapters'
    | '/novels/$novelId/characters'
    | '/novels/$novelId/continuity'
    | '/novels/$novelId/factions'
    | '/novels/$novelId/locations'
    | '/novels/$novelId/lore'
    | '/novels/$novelId/magic'
    | '/novels/$novelId/overview'
    | '/novels/$novelId/plot'
    | '/novels/$novelId/species'
    | '/novels/$novelId/story-bible'
    | '/novels/$novelId/timeline'
    | '/novels/$novelId/versions'
    | '/novels/$novelId/volumes'
    | '/novels/$novelId/world'
    | '/novels/$novelId/'
    | '/novels/$novelId/character/$characterId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/profile'
    | '/projects'
    | '/settings'
    | '/sitemap'
    | '/'
    | '/novels/$novelId/approvals'
    | '/novels/$novelId/assets'
    | '/novels/$novelId/chapter-brief'
    | '/novels/$novelId/chapter-editor'
    | '/novels/$novelId/chapter-generate'
    | '/novels/$novelId/chapter-review'
    | '/novels/$novelId/chapters'
    | '/novels/$novelId/characters'
    | '/novels/$novelId/continuity'
    | '/novels/$novelId/factions'
    | '/novels/$novelId/locations'
    | '/novels/$novelId/lore'
    | '/novels/$novelId/magic'
    | '/novels/$novelId/overview'
    | '/novels/$novelId/plot'
    | '/novels/$novelId/species'
    | '/novels/$novelId/story-bible'
    | '/novels/$novelId/timeline'
    | '/novels/$novelId/versions'
    | '/novels/$novelId/volumes'
    | '/novels/$novelId/world'
    | '/novels/$novelId'
    | '/novels/$novelId/character/$characterId'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/_app/profile'
    | '/_app/projects'
    | '/_app/settings'
    | '/_app/sitemap'
    | '/novels/$novelId'
    | '/_app/'
    | '/novels/$novelId/approvals'
    | '/novels/$novelId/assets'
    | '/novels/$novelId/chapter-brief'
    | '/novels/$novelId/chapter-editor'
    | '/novels/$novelId/chapter-generate'
    | '/novels/$novelId/chapter-review'
    | '/novels/$novelId/chapters'
    | '/novels/$novelId/characters'
    | '/novels/$novelId/continuity'
    | '/novels/$novelId/factions'
    | '/novels/$novelId/locations'
    | '/novels/$novelId/lore'
    | '/novels/$novelId/magic'
    | '/novels/$novelId/overview'
    | '/novels/$novelId/plot'
    | '/novels/$novelId/species'
    | '/novels/$novelId/story-bible'
    | '/novels/$novelId/timeline'
    | '/novels/$novelId/versions'
    | '/novels/$novelId/volumes'
    | '/novels/$novelId/world'
    | '/novels/$novelId/'
    | '/novels/$novelId/character/$characterId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  NovelsNovelIdRoute: typeof NovelsNovelIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/novels/$novelId': {
      id: '/novels/$novelId'
      path: '/novels/$novelId'
      fullPath: '/novels/$novelId'
      preLoaderRoute: typeof NovelsNovelIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/sitemap': {
      id: '/_app/sitemap'
      path: '/sitemap'
      fullPath: '/sitemap'
      preLoaderRoute: typeof AppSitemapRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/projects': {
      id: '/_app/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof AppProjectsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/novels/$novelId/': {
      id: '/novels/$novelId/'
      path: '/'
      fullPath: '/novels/$novelId/'
      preLoaderRoute: typeof NovelsNovelIdIndexRouteImport
      parentRoute: typeof NovelsNovelIdRoute
    }
    '/novels/$novelId/world': {
      id: '/novels/$novelId/world'
      path: '/world'
      fullPath: '/novels/$novelId/world'
      preLoaderRoute: typeof NovelsNovelIdWorldRouteImport
      parentRoute: typeof NovelsNovelIdRoute
    }
    '/novels/$novelId/volumes': {
      id: '/novels/$novelId/volumes'
      path: '/volumes'
      fullPath: '/novels/$novelId/volumes'
      preLoaderRoute: typeof NovelsNovelIdVolumesRouteImport
      parentRoute: typeof NovelsNovelIdRoute
    }
    '/novels/$novelId/versions': {
      id: '/novels/$novelId/versions'
      path: '/versions'
      fullPath: '/novels/$novelId/versions'
      preLoaderRoute: typeof NovelsNovelIdVersionsRouteImport
      parentRoute: typeof NovelsNovelIdRoute
    }
    '/novels/$novelId/timeline': {
      id: '/novels/$novelId/timeline'
      path: '/timeline'
      fullPath: '/novels/$novelId/timeline'
      preLoaderRoute: typeof NovelsNovelIdTimelineRouteImport
      parentRoute: typeof NovelsNovelIdRoute
    }
    '/novels/$novelId/story-bible': {
      id: '/novels/$novelId/story-bible'
      path: '/story-bible'
      fullPath: '/novels/$novelId/story-bible'
      preLoaderRoute: typeof NovelsNovelIdStoryBibleRouteImport
      parentRoute: typeof NovelsNovelIdRoute
    }
    '/novels/$novelId/species': {
      id: '/novels/$novelId/species'
      path: '/species'
      fullPath: '/novels/$novelId/species'
      preLoaderRoute: typeof NovelsNovelIdSpeciesRouteImport
      parentRoute: typeof NovelsNovelIdRoute
    }
    '/novels/$novelId/plot': {
      id: '/novels/$novelId/plot'
      path: '/plot'
      fullPath: '/novels/$novelId/plot'
      preLoaderRoute: typeof NovelsNovelIdPlotRouteImport
      parentRoute: typeof NovelsNovelIdRoute
    }
    '/novels/$novelId/overview': {
      id: '/novels/$novelId/overview'
      path: '/overview'
      fullPath: '/novels/$novelId/overview'
      preLoaderRoute: typeof NovelsNovelIdOverviewRouteImport
      parentRoute: typeof NovelsNovelIdRoute
    }
    '/novels/$novelId/magic': {
      id: '/novels/$novelId/magic'
      path: '/magic'
      fullPath: '/novels/$novelId/magic'
      preLoaderRoute: typeof NovelsNovelIdMagicRouteImport
      parentRoute: typeof NovelsNovelIdRoute
    }
    '/novels/$novelId/lore': {
      id: '/novels/$novelId/lore'
      path: '/lore'
      fullPath: '/novels/$novelId/lore'
      preLoaderRoute: typeof NovelsNovelIdLoreRouteImport
      parentRoute: typeof NovelsNovelIdRoute
    }
    '/novels/$novelId/locations': {
      id: '/novels/$novelId/locations'
      path: '/locations'
      fullPath: '/novels/$novelId/locations'
      preLoaderRoute: typeof NovelsNovelIdLocationsRouteImport
      parentRoute: typeof NovelsNovelIdRoute
    }
    '/novels/$novelId/factions': {
      id: '/novels/$novelId/factions'
      path: '/factions'
      fullPath: '/novels/$novelId/factions'
      preLoaderRoute: typeof NovelsNovelIdFactionsRouteImport
      parentRoute: typeof NovelsNovelIdRoute
    }
    '/novels/$novelId/continuity': {
      id: '/novels/$novelId/continuity'
      path: '/continuity'
      fullPath: '/novels/$novelId/continuity'
      preLoaderRoute: typeof NovelsNovelIdContinuityRouteImport
      parentRoute: typeof NovelsNovelIdRoute
    }
    '/novels/$novelId/characters': {
      id: '/novels/$novelId/characters'
      path: '/characters'
      fullPath: '/novels/$novelId/characters'
      preLoaderRoute: typeof NovelsNovelIdCharactersRouteImport
      parentRoute: typeof NovelsNovelIdRoute
    }
    '/novels/$novelId/chapters': {
      id: '/novels/$novelId/chapters'
      path: '/chapters'
      fullPath: '/novels/$novelId/chapters'
      preLoaderRoute: typeof NovelsNovelIdChaptersRouteImport
      parentRoute: typeof NovelsNovelIdRoute
    }
    '/novels/$novelId/chapter-review': {
      id: '/novels/$novelId/chapter-review'
      path: '/chapter-review'
      fullPath: '/novels/$novelId/chapter-review'
      preLoaderRoute: typeof NovelsNovelIdChapterReviewRouteImport
      parentRoute: typeof NovelsNovelIdRoute
    }
    '/novels/$novelId/chapter-generate': {
      id: '/novels/$novelId/chapter-generate'
      path: '/chapter-generate'
      fullPath: '/novels/$novelId/chapter-generate'
      preLoaderRoute: typeof NovelsNovelIdChapterGenerateRouteImport
      parentRoute: typeof NovelsNovelIdRoute
    }
    '/novels/$novelId/chapter-editor': {
      id: '/novels/$novelId/chapter-editor'
      path: '/chapter-editor'
      fullPath: '/novels/$novelId/chapter-editor'
      preLoaderRoute: typeof NovelsNovelIdChapterEditorRouteImport
      parentRoute: typeof NovelsNovelIdRoute
    }
    '/novels/$novelId/chapter-brief': {
      id: '/novels/$novelId/chapter-brief'
      path: '/chapter-brief'
      fullPath: '/novels/$novelId/chapter-brief'
      preLoaderRoute: typeof NovelsNovelIdChapterBriefRouteImport
      parentRoute: typeof NovelsNovelIdRoute
    }
    '/novels/$novelId/assets': {
      id: '/novels/$novelId/assets'
      path: '/assets'
      fullPath: '/novels/$novelId/assets'
      preLoaderRoute: typeof NovelsNovelIdAssetsRouteImport
      parentRoute: typeof NovelsNovelIdRoute
    }
    '/novels/$novelId/approvals': {
      id: '/novels/$novelId/approvals'
      path: '/approvals'
      fullPath: '/novels/$novelId/approvals'
      preLoaderRoute: typeof NovelsNovelIdApprovalsRouteImport
      parentRoute: typeof NovelsNovelIdRoute
    }
    '/novels/$novelId/character/$characterId': {
      id: '/novels/$novelId/character/$characterId'
      path: '/character/$characterId'
      fullPath: '/novels/$novelId/character/$characterId'
      preLoaderRoute: typeof NovelsNovelIdCharacterCharacterIdRouteImport
      parentRoute: typeof NovelsNovelIdRoute
    }
  }
}

interface AppRouteChildren {
  AppProfileRoute: typeof AppProfileRoute
  AppProjectsRoute: typeof AppProjectsRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppSitemapRoute: typeof AppSitemapRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppProfileRoute: AppProfileRoute,
  AppProjectsRoute: AppProjectsRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppSitemapRoute: AppSitemapRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface NovelsNovelIdRouteChildren {
  NovelsNovelIdApprovalsRoute: typeof NovelsNovelIdApprovalsRoute
  NovelsNovelIdAssetsRoute: typeof NovelsNovelIdAssetsRoute
  NovelsNovelIdChapterBriefRoute: typeof NovelsNovelIdChapterBriefRoute
  NovelsNovelIdChapterEditorRoute: typeof NovelsNovelIdChapterEditorRoute
  NovelsNovelIdChapterGenerateRoute: typeof NovelsNovelIdChapterGenerateRoute
  NovelsNovelIdChapterReviewRoute: typeof NovelsNovelIdChapterReviewRoute
  NovelsNovelIdChaptersRoute: typeof NovelsNovelIdChaptersRoute
  NovelsNovelIdCharactersRoute: typeof NovelsNovelIdCharactersRoute
  NovelsNovelIdContinuityRoute: typeof NovelsNovelIdContinuityRoute
  NovelsNovelIdFactionsRoute: typeof NovelsNovelIdFactionsRoute
  NovelsNovelIdLocationsRoute: typeof NovelsNovelIdLocationsRoute
  NovelsNovelIdLoreRoute: typeof NovelsNovelIdLoreRoute
  NovelsNovelIdMagicRoute: typeof NovelsNovelIdMagicRoute
  NovelsNovelIdOverviewRoute: typeof NovelsNovelIdOverviewRoute
  NovelsNovelIdPlotRoute: typeof NovelsNovelIdPlotRoute
  NovelsNovelIdSpeciesRoute: typeof NovelsNovelIdSpeciesRoute
  NovelsNovelIdStoryBibleRoute: typeof NovelsNovelIdStoryBibleRoute
  NovelsNovelIdTimelineRoute: typeof NovelsNovelIdTimelineRoute
  NovelsNovelIdVersionsRoute: typeof NovelsNovelIdVersionsRoute
  NovelsNovelIdVolumesRoute: typeof NovelsNovelIdVolumesRoute
  NovelsNovelIdWorldRoute: typeof NovelsNovelIdWorldRoute
  NovelsNovelIdIndexRoute: typeof NovelsNovelIdIndexRoute
  NovelsNovelIdCharacterCharacterIdRoute: typeof NovelsNovelIdCharacterCharacterIdRoute
}

const NovelsNovelIdRouteChildren: NovelsNovelIdRouteChildren = {
  NovelsNovelIdApprovalsRoute: NovelsNovelIdApprovalsRoute,
  NovelsNovelIdAssetsRoute: NovelsNovelIdAssetsRoute,
  NovelsNovelIdChapterBriefRoute: NovelsNovelIdChapterBriefRoute,
  NovelsNovelIdChapterEditorRoute: NovelsNovelIdChapterEditorRoute,
  NovelsNovelIdChapterGenerateRoute: NovelsNovelIdChapterGenerateRoute,
  NovelsNovelIdChapterReviewRoute: NovelsNovelIdChapterReviewRoute,
  NovelsNovelIdChaptersRoute: NovelsNovelIdChaptersRoute,
  NovelsNovelIdCharactersRoute: NovelsNovelIdCharactersRoute,
  NovelsNovelIdContinuityRoute: NovelsNovelIdContinuityRoute,
  NovelsNovelIdFactionsRoute: NovelsNovelIdFactionsRoute,
  NovelsNovelIdLocationsRoute: NovelsNovelIdLocationsRoute,
  NovelsNovelIdLoreRoute: NovelsNovelIdLoreRoute,
  NovelsNovelIdMagicRoute: NovelsNovelIdMagicRoute,
  NovelsNovelIdOverviewRoute: NovelsNovelIdOverviewRoute,
  NovelsNovelIdPlotRoute: NovelsNovelIdPlotRoute,
  NovelsNovelIdSpeciesRoute: NovelsNovelIdSpeciesRoute,
  NovelsNovelIdStoryBibleRoute: NovelsNovelIdStoryBibleRoute,
  NovelsNovelIdTimelineRoute: NovelsNovelIdTimelineRoute,
  NovelsNovelIdVersionsRoute: NovelsNovelIdVersionsRoute,
  NovelsNovelIdVolumesRoute: NovelsNovelIdVolumesRoute,
  NovelsNovelIdWorldRoute: NovelsNovelIdWorldRoute,
  NovelsNovelIdIndexRoute: NovelsNovelIdIndexRoute,
  NovelsNovelIdCharacterCharacterIdRoute:
    NovelsNovelIdCharacterCharacterIdRoute,
}

const NovelsNovelIdRouteWithChildren = NovelsNovelIdRoute._addFileChildren(
  NovelsNovelIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  NovelsNovelIdRoute: NovelsNovelIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
