/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ConsoleRouteImport } from './routes/console'
import { Route as PortalRouteImport } from './routes/_portal'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ConsoleIndexRouteImport } from './routes/console/index'
import { Route as InviteTokenRouteImport } from './routes/invite.$token'
import { Route as ConsoleWebhooksRouteImport } from './routes/console/webhooks'
import { Route as ConsoleUsersRouteImport } from './routes/console/users'
import { Route as ConsoleSamlRouteImport } from './routes/console/saml'
import { Route as ConsoleRolesRouteImport } from './routes/console/roles'
import { Route as ConsoleResourcesRouteImport } from './routes/console/resources'
import { Route as ConsoleClientsRouteImport } from './routes/console/clients'
import { Route as ConsoleApplicationsRouteImport } from './routes/console/applications'
import { Route as PortalApplicationsRouteImport } from './routes/_portal/applications'
import { Route as AuthRegisterRouteImport } from './routes/_auth/register'
import { Route as AuthRecoverRouteImport } from './routes/_auth/recover'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as AuthErrorRouteImport } from './routes/_auth/error'
import { Route as AuthConsentRouteImport } from './routes/_auth/consent'
import { Route as PortalOrganizationsIndexRouteImport } from './routes/_portal/organizations/index'
import { Route as PortalAccountIndexRouteImport } from './routes/_portal/account/index'
import { Route as ConsoleUsersUserIdRouteImport } from './routes/console/users.$userId'
import { Route as ConsoleApplicationsAppIdRouteImport } from './routes/console/applications.$appId'
import { Route as PortalOrganizationsOrgIdRouteImport } from './routes/_portal/organizations/$orgId'
import { Route as PortalAccountSessionsRouteImport } from './routes/_portal/account/sessions'
import { Route as PortalAccountSecurityRouteImport } from './routes/_portal/account/security'
import { Route as PortalAccountProfileRouteImport } from './routes/_portal/account/profile'
import { Route as PortalAccountContactsRouteImport } from './routes/_portal/account/contacts'
import { Route as PortalAccountConnectedRouteImport } from './routes/_portal/account/connected'
import { Route as PortalOrganizationsOrgIdIndexRouteImport } from './routes/_portal/organizations/$orgId/index'
import { Route as PortalOrganizationsOrgIdSettingsRouteImport } from './routes/_portal/organizations/$orgId/settings'
import { Route as PortalOrganizationsOrgIdProvidersRouteImport } from './routes/_portal/organizations/$orgId/providers'
import { Route as PortalOrganizationsOrgIdMembersRouteImport } from './routes/_portal/organizations/$orgId/members'
import { Route as PortalOrganizationsOrgIdDomainsRouteImport } from './routes/_portal/organizations/$orgId/domains'

const ConsoleRoute = ConsoleRouteImport.update({
  id: '/console',
  path: '/console',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalRoute = PortalRouteImport.update({
  id: '/_portal',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsoleIndexRoute = ConsoleIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ConsoleRoute,
} as any)
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsoleWebhooksRoute = ConsoleWebhooksRouteImport.update({
  id: '/webhooks',
  path: '/webhooks',
  getParentRoute: () => ConsoleRoute,
} as any)
const ConsoleUsersRoute = ConsoleUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => ConsoleRoute,
} as any)
const ConsoleSamlRoute = ConsoleSamlRouteImport.update({
  id: '/saml',
  path: '/saml',
  getParentRoute: () => ConsoleRoute,
} as any)
const ConsoleRolesRoute = ConsoleRolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => ConsoleRoute,
} as any)
const ConsoleResourcesRoute = ConsoleResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => ConsoleRoute,
} as any)
const ConsoleClientsRoute = ConsoleClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => ConsoleRoute,
} as any)
const ConsoleApplicationsRoute = ConsoleApplicationsRouteImport.update({
  id: '/applications',
  path: '/applications',
  getParentRoute: () => ConsoleRoute,
} as any)
const PortalApplicationsRoute = PortalApplicationsRouteImport.update({
  id: '/applications',
  path: '/applications',
  getParentRoute: () => PortalRoute,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthRoute,
} as any)
const AuthRecoverRoute = AuthRecoverRouteImport.update({
  id: '/recover',
  path: '/recover',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AuthErrorRoute = AuthErrorRouteImport.update({
  id: '/error',
  path: '/error',
  getParentRoute: () => AuthRoute,
} as any)
const AuthConsentRoute = AuthConsentRouteImport.update({
  id: '/consent',
  path: '/consent',
  getParentRoute: () => AuthRoute,
} as any)
const PortalOrganizationsIndexRoute =
  PortalOrganizationsIndexRouteImport.update({
    id: '/organizations/',
    path: '/organizations/',
    getParentRoute: () => PortalRoute,
  } as any)
const PortalAccountIndexRoute = PortalAccountIndexRouteImport.update({
  id: '/account/',
  path: '/account/',
  getParentRoute: () => PortalRoute,
} as any)
const ConsoleUsersUserIdRoute = ConsoleUsersUserIdRouteImport.update({
  id: '/$userId',
  path: '/$userId',
  getParentRoute: () => ConsoleUsersRoute,
} as any)
const ConsoleApplicationsAppIdRoute =
  ConsoleApplicationsAppIdRouteImport.update({
    id: '/$appId',
    path: '/$appId',
    getParentRoute: () => ConsoleApplicationsRoute,
  } as any)
const PortalOrganizationsOrgIdRoute =
  PortalOrganizationsOrgIdRouteImport.update({
    id: '/organizations/$orgId',
    path: '/organizations/$orgId',
    getParentRoute: () => PortalRoute,
  } as any)
const PortalAccountSessionsRoute = PortalAccountSessionsRouteImport.update({
  id: '/account/sessions',
  path: '/account/sessions',
  getParentRoute: () => PortalRoute,
} as any)
const PortalAccountSecurityRoute = PortalAccountSecurityRouteImport.update({
  id: '/account/security',
  path: '/account/security',
  getParentRoute: () => PortalRoute,
} as any)
const PortalAccountProfileRoute = PortalAccountProfileRouteImport.update({
  id: '/account/profile',
  path: '/account/profile',
  getParentRoute: () => PortalRoute,
} as any)
const PortalAccountContactsRoute = PortalAccountContactsRouteImport.update({
  id: '/account/contacts',
  path: '/account/contacts',
  getParentRoute: () => PortalRoute,
} as any)
const PortalAccountConnectedRoute = PortalAccountConnectedRouteImport.update({
  id: '/account/connected',
  path: '/account/connected',
  getParentRoute: () => PortalRoute,
} as any)
const PortalOrganizationsOrgIdIndexRoute =
  PortalOrganizationsOrgIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => PortalOrganizationsOrgIdRoute,
  } as any)
const PortalOrganizationsOrgIdSettingsRoute =
  PortalOrganizationsOrgIdSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => PortalOrganizationsOrgIdRoute,
  } as any)
const PortalOrganizationsOrgIdProvidersRoute =
  PortalOrganizationsOrgIdProvidersRouteImport.update({
    id: '/providers',
    path: '/providers',
    getParentRoute: () => PortalOrganizationsOrgIdRoute,
  } as any)
const PortalOrganizationsOrgIdMembersRoute =
  PortalOrganizationsOrgIdMembersRouteImport.update({
    id: '/members',
    path: '/members',
    getParentRoute: () => PortalOrganizationsOrgIdRoute,
  } as any)
const PortalOrganizationsOrgIdDomainsRoute =
  PortalOrganizationsOrgIdDomainsRouteImport.update({
    id: '/domains',
    path: '/domains',
    getParentRoute: () => PortalOrganizationsOrgIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/console': typeof ConsoleRouteWithChildren
  '/consent': typeof AuthConsentRoute
  '/error': typeof AuthErrorRoute
  '/login': typeof AuthLoginRoute
  '/recover': typeof AuthRecoverRoute
  '/register': typeof AuthRegisterRoute
  '/applications': typeof PortalApplicationsRoute
  '/console/applications': typeof ConsoleApplicationsRouteWithChildren
  '/console/clients': typeof ConsoleClientsRoute
  '/console/resources': typeof ConsoleResourcesRoute
  '/console/roles': typeof ConsoleRolesRoute
  '/console/saml': typeof ConsoleSamlRoute
  '/console/users': typeof ConsoleUsersRouteWithChildren
  '/console/webhooks': typeof ConsoleWebhooksRoute
  '/invite/$token': typeof InviteTokenRoute
  '/console/': typeof ConsoleIndexRoute
  '/account/connected': typeof PortalAccountConnectedRoute
  '/account/contacts': typeof PortalAccountContactsRoute
  '/account/profile': typeof PortalAccountProfileRoute
  '/account/security': typeof PortalAccountSecurityRoute
  '/account/sessions': typeof PortalAccountSessionsRoute
  '/organizations/$orgId': typeof PortalOrganizationsOrgIdRouteWithChildren
  '/console/applications/$appId': typeof ConsoleApplicationsAppIdRoute
  '/console/users/$userId': typeof ConsoleUsersUserIdRoute
  '/account/': typeof PortalAccountIndexRoute
  '/organizations/': typeof PortalOrganizationsIndexRoute
  '/organizations/$orgId/domains': typeof PortalOrganizationsOrgIdDomainsRoute
  '/organizations/$orgId/members': typeof PortalOrganizationsOrgIdMembersRoute
  '/organizations/$orgId/providers': typeof PortalOrganizationsOrgIdProvidersRoute
  '/organizations/$orgId/settings': typeof PortalOrganizationsOrgIdSettingsRoute
  '/organizations/$orgId/': typeof PortalOrganizationsOrgIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/consent': typeof AuthConsentRoute
  '/error': typeof AuthErrorRoute
  '/login': typeof AuthLoginRoute
  '/recover': typeof AuthRecoverRoute
  '/register': typeof AuthRegisterRoute
  '/applications': typeof PortalApplicationsRoute
  '/console/applications': typeof ConsoleApplicationsRouteWithChildren
  '/console/clients': typeof ConsoleClientsRoute
  '/console/resources': typeof ConsoleResourcesRoute
  '/console/roles': typeof ConsoleRolesRoute
  '/console/saml': typeof ConsoleSamlRoute
  '/console/users': typeof ConsoleUsersRouteWithChildren
  '/console/webhooks': typeof ConsoleWebhooksRoute
  '/invite/$token': typeof InviteTokenRoute
  '/console': typeof ConsoleIndexRoute
  '/account/connected': typeof PortalAccountConnectedRoute
  '/account/contacts': typeof PortalAccountContactsRoute
  '/account/profile': typeof PortalAccountProfileRoute
  '/account/security': typeof PortalAccountSecurityRoute
  '/account/sessions': typeof PortalAccountSessionsRoute
  '/console/applications/$appId': typeof ConsoleApplicationsAppIdRoute
  '/console/users/$userId': typeof ConsoleUsersUserIdRoute
  '/account': typeof PortalAccountIndexRoute
  '/organizations': typeof PortalOrganizationsIndexRoute
  '/organizations/$orgId/domains': typeof PortalOrganizationsOrgIdDomainsRoute
  '/organizations/$orgId/members': typeof PortalOrganizationsOrgIdMembersRoute
  '/organizations/$orgId/providers': typeof PortalOrganizationsOrgIdProvidersRoute
  '/organizations/$orgId/settings': typeof PortalOrganizationsOrgIdSettingsRoute
  '/organizations/$orgId': typeof PortalOrganizationsOrgIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/_portal': typeof PortalRouteWithChildren
  '/console': typeof ConsoleRouteWithChildren
  '/_auth/consent': typeof AuthConsentRoute
  '/_auth/error': typeof AuthErrorRoute
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/recover': typeof AuthRecoverRoute
  '/_auth/register': typeof AuthRegisterRoute
  '/_portal/applications': typeof PortalApplicationsRoute
  '/console/applications': typeof ConsoleApplicationsRouteWithChildren
  '/console/clients': typeof ConsoleClientsRoute
  '/console/resources': typeof ConsoleResourcesRoute
  '/console/roles': typeof ConsoleRolesRoute
  '/console/saml': typeof ConsoleSamlRoute
  '/console/users': typeof ConsoleUsersRouteWithChildren
  '/console/webhooks': typeof ConsoleWebhooksRoute
  '/invite/$token': typeof InviteTokenRoute
  '/console/': typeof ConsoleIndexRoute
  '/_portal/account/connected': typeof PortalAccountConnectedRoute
  '/_portal/account/contacts': typeof PortalAccountContactsRoute
  '/_portal/account/profile': typeof PortalAccountProfileRoute
  '/_portal/account/security': typeof PortalAccountSecurityRoute
  '/_portal/account/sessions': typeof PortalAccountSessionsRoute
  '/_portal/organizations/$orgId': typeof PortalOrganizationsOrgIdRouteWithChildren
  '/console/applications/$appId': typeof ConsoleApplicationsAppIdRoute
  '/console/users/$userId': typeof ConsoleUsersUserIdRoute
  '/_portal/account/': typeof PortalAccountIndexRoute
  '/_portal/organizations/': typeof PortalOrganizationsIndexRoute
  '/_portal/organizations/$orgId/domains': typeof PortalOrganizationsOrgIdDomainsRoute
  '/_portal/organizations/$orgId/members': typeof PortalOrganizationsOrgIdMembersRoute
  '/_portal/organizations/$orgId/providers': typeof PortalOrganizationsOrgIdProvidersRoute
  '/_portal/organizations/$orgId/settings': typeof PortalOrganizationsOrgIdSettingsRoute
  '/_portal/organizations/$orgId/': typeof PortalOrganizationsOrgIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/console'
    | '/consent'
    | '/error'
    | '/login'
    | '/recover'
    | '/register'
    | '/applications'
    | '/console/applications'
    | '/console/clients'
    | '/console/resources'
    | '/console/roles'
    | '/console/saml'
    | '/console/users'
    | '/console/webhooks'
    | '/invite/$token'
    | '/console/'
    | '/account/connected'
    | '/account/contacts'
    | '/account/profile'
    | '/account/security'
    | '/account/sessions'
    | '/organizations/$orgId'
    | '/console/applications/$appId'
    | '/console/users/$userId'
    | '/account/'
    | '/organizations/'
    | '/organizations/$orgId/domains'
    | '/organizations/$orgId/members'
    | '/organizations/$orgId/providers'
    | '/organizations/$orgId/settings'
    | '/organizations/$orgId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/consent'
    | '/error'
    | '/login'
    | '/recover'
    | '/register'
    | '/applications'
    | '/console/applications'
    | '/console/clients'
    | '/console/resources'
    | '/console/roles'
    | '/console/saml'
    | '/console/users'
    | '/console/webhooks'
    | '/invite/$token'
    | '/console'
    | '/account/connected'
    | '/account/contacts'
    | '/account/profile'
    | '/account/security'
    | '/account/sessions'
    | '/console/applications/$appId'
    | '/console/users/$userId'
    | '/account'
    | '/organizations'
    | '/organizations/$orgId/domains'
    | '/organizations/$orgId/members'
    | '/organizations/$orgId/providers'
    | '/organizations/$orgId/settings'
    | '/organizations/$orgId'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/_portal'
    | '/console'
    | '/_auth/consent'
    | '/_auth/error'
    | '/_auth/login'
    | '/_auth/recover'
    | '/_auth/register'
    | '/_portal/applications'
    | '/console/applications'
    | '/console/clients'
    | '/console/resources'
    | '/console/roles'
    | '/console/saml'
    | '/console/users'
    | '/console/webhooks'
    | '/invite/$token'
    | '/console/'
    | '/_portal/account/connected'
    | '/_portal/account/contacts'
    | '/_portal/account/profile'
    | '/_portal/account/security'
    | '/_portal/account/sessions'
    | '/_portal/organizations/$orgId'
    | '/console/applications/$appId'
    | '/console/users/$userId'
    | '/_portal/account/'
    | '/_portal/organizations/'
    | '/_portal/organizations/$orgId/domains'
    | '/_portal/organizations/$orgId/members'
    | '/_portal/organizations/$orgId/providers'
    | '/_portal/organizations/$orgId/settings'
    | '/_portal/organizations/$orgId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  PortalRoute: typeof PortalRouteWithChildren
  ConsoleRoute: typeof ConsoleRouteWithChildren
  InviteTokenRoute: typeof InviteTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/console': {
      id: '/console'
      path: '/console'
      fullPath: '/console'
      preLoaderRoute: typeof ConsoleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_portal': {
      id: '/_portal'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/console/': {
      id: '/console/'
      path: '/'
      fullPath: '/console/'
      preLoaderRoute: typeof ConsoleIndexRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/invite/$token': {
      id: '/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof InviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/console/webhooks': {
      id: '/console/webhooks'
      path: '/webhooks'
      fullPath: '/console/webhooks'
      preLoaderRoute: typeof ConsoleWebhooksRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/console/users': {
      id: '/console/users'
      path: '/users'
      fullPath: '/console/users'
      preLoaderRoute: typeof ConsoleUsersRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/console/saml': {
      id: '/console/saml'
      path: '/saml'
      fullPath: '/console/saml'
      preLoaderRoute: typeof ConsoleSamlRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/console/roles': {
      id: '/console/roles'
      path: '/roles'
      fullPath: '/console/roles'
      preLoaderRoute: typeof ConsoleRolesRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/console/resources': {
      id: '/console/resources'
      path: '/resources'
      fullPath: '/console/resources'
      preLoaderRoute: typeof ConsoleResourcesRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/console/clients': {
      id: '/console/clients'
      path: '/clients'
      fullPath: '/console/clients'
      preLoaderRoute: typeof ConsoleClientsRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/console/applications': {
      id: '/console/applications'
      path: '/applications'
      fullPath: '/console/applications'
      preLoaderRoute: typeof ConsoleApplicationsRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/_portal/applications': {
      id: '/_portal/applications'
      path: '/applications'
      fullPath: '/applications'
      preLoaderRoute: typeof PortalApplicationsRouteImport
      parentRoute: typeof PortalRoute
    }
    '/_auth/register': {
      id: '/_auth/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/recover': {
      id: '/_auth/recover'
      path: '/recover'
      fullPath: '/recover'
      preLoaderRoute: typeof AuthRecoverRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/error': {
      id: '/_auth/error'
      path: '/error'
      fullPath: '/error'
      preLoaderRoute: typeof AuthErrorRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/consent': {
      id: '/_auth/consent'
      path: '/consent'
      fullPath: '/consent'
      preLoaderRoute: typeof AuthConsentRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_portal/organizations/': {
      id: '/_portal/organizations/'
      path: '/organizations'
      fullPath: '/organizations/'
      preLoaderRoute: typeof PortalOrganizationsIndexRouteImport
      parentRoute: typeof PortalRoute
    }
    '/_portal/account/': {
      id: '/_portal/account/'
      path: '/account'
      fullPath: '/account/'
      preLoaderRoute: typeof PortalAccountIndexRouteImport
      parentRoute: typeof PortalRoute
    }
    '/console/users/$userId': {
      id: '/console/users/$userId'
      path: '/$userId'
      fullPath: '/console/users/$userId'
      preLoaderRoute: typeof ConsoleUsersUserIdRouteImport
      parentRoute: typeof ConsoleUsersRoute
    }
    '/console/applications/$appId': {
      id: '/console/applications/$appId'
      path: '/$appId'
      fullPath: '/console/applications/$appId'
      preLoaderRoute: typeof ConsoleApplicationsAppIdRouteImport
      parentRoute: typeof ConsoleApplicationsRoute
    }
    '/_portal/organizations/$orgId': {
      id: '/_portal/organizations/$orgId'
      path: '/organizations/$orgId'
      fullPath: '/organizations/$orgId'
      preLoaderRoute: typeof PortalOrganizationsOrgIdRouteImport
      parentRoute: typeof PortalRoute
    }
    '/_portal/account/sessions': {
      id: '/_portal/account/sessions'
      path: '/account/sessions'
      fullPath: '/account/sessions'
      preLoaderRoute: typeof PortalAccountSessionsRouteImport
      parentRoute: typeof PortalRoute
    }
    '/_portal/account/security': {
      id: '/_portal/account/security'
      path: '/account/security'
      fullPath: '/account/security'
      preLoaderRoute: typeof PortalAccountSecurityRouteImport
      parentRoute: typeof PortalRoute
    }
    '/_portal/account/profile': {
      id: '/_portal/account/profile'
      path: '/account/profile'
      fullPath: '/account/profile'
      preLoaderRoute: typeof PortalAccountProfileRouteImport
      parentRoute: typeof PortalRoute
    }
    '/_portal/account/contacts': {
      id: '/_portal/account/contacts'
      path: '/account/contacts'
      fullPath: '/account/contacts'
      preLoaderRoute: typeof PortalAccountContactsRouteImport
      parentRoute: typeof PortalRoute
    }
    '/_portal/account/connected': {
      id: '/_portal/account/connected'
      path: '/account/connected'
      fullPath: '/account/connected'
      preLoaderRoute: typeof PortalAccountConnectedRouteImport
      parentRoute: typeof PortalRoute
    }
    '/_portal/organizations/$orgId/': {
      id: '/_portal/organizations/$orgId/'
      path: '/'
      fullPath: '/organizations/$orgId/'
      preLoaderRoute: typeof PortalOrganizationsOrgIdIndexRouteImport
      parentRoute: typeof PortalOrganizationsOrgIdRoute
    }
    '/_portal/organizations/$orgId/settings': {
      id: '/_portal/organizations/$orgId/settings'
      path: '/settings'
      fullPath: '/organizations/$orgId/settings'
      preLoaderRoute: typeof PortalOrganizationsOrgIdSettingsRouteImport
      parentRoute: typeof PortalOrganizationsOrgIdRoute
    }
    '/_portal/organizations/$orgId/providers': {
      id: '/_portal/organizations/$orgId/providers'
      path: '/providers'
      fullPath: '/organizations/$orgId/providers'
      preLoaderRoute: typeof PortalOrganizationsOrgIdProvidersRouteImport
      parentRoute: typeof PortalOrganizationsOrgIdRoute
    }
    '/_portal/organizations/$orgId/members': {
      id: '/_portal/organizations/$orgId/members'
      path: '/members'
      fullPath: '/organizations/$orgId/members'
      preLoaderRoute: typeof PortalOrganizationsOrgIdMembersRouteImport
      parentRoute: typeof PortalOrganizationsOrgIdRoute
    }
    '/_portal/organizations/$orgId/domains': {
      id: '/_portal/organizations/$orgId/domains'
      path: '/domains'
      fullPath: '/organizations/$orgId/domains'
      preLoaderRoute: typeof PortalOrganizationsOrgIdDomainsRouteImport
      parentRoute: typeof PortalOrganizationsOrgIdRoute
    }
  }
}

interface AuthRouteChildren {
  AuthConsentRoute: typeof AuthConsentRoute
  AuthErrorRoute: typeof AuthErrorRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRecoverRoute: typeof AuthRecoverRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthConsentRoute: AuthConsentRoute,
  AuthErrorRoute: AuthErrorRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRecoverRoute: AuthRecoverRoute,
  AuthRegisterRoute: AuthRegisterRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface PortalOrganizationsOrgIdRouteChildren {
  PortalOrganizationsOrgIdDomainsRoute: typeof PortalOrganizationsOrgIdDomainsRoute
  PortalOrganizationsOrgIdMembersRoute: typeof PortalOrganizationsOrgIdMembersRoute
  PortalOrganizationsOrgIdProvidersRoute: typeof PortalOrganizationsOrgIdProvidersRoute
  PortalOrganizationsOrgIdSettingsRoute: typeof PortalOrganizationsOrgIdSettingsRoute
  PortalOrganizationsOrgIdIndexRoute: typeof PortalOrganizationsOrgIdIndexRoute
}

const PortalOrganizationsOrgIdRouteChildren: PortalOrganizationsOrgIdRouteChildren =
  {
    PortalOrganizationsOrgIdDomainsRoute: PortalOrganizationsOrgIdDomainsRoute,
    PortalOrganizationsOrgIdMembersRoute: PortalOrganizationsOrgIdMembersRoute,
    PortalOrganizationsOrgIdProvidersRoute:
      PortalOrganizationsOrgIdProvidersRoute,
    PortalOrganizationsOrgIdSettingsRoute:
      PortalOrganizationsOrgIdSettingsRoute,
    PortalOrganizationsOrgIdIndexRoute: PortalOrganizationsOrgIdIndexRoute,
  }

const PortalOrganizationsOrgIdRouteWithChildren =
  PortalOrganizationsOrgIdRoute._addFileChildren(
    PortalOrganizationsOrgIdRouteChildren,
  )

interface PortalRouteChildren {
  PortalApplicationsRoute: typeof PortalApplicationsRoute
  PortalAccountConnectedRoute: typeof PortalAccountConnectedRoute
  PortalAccountContactsRoute: typeof PortalAccountContactsRoute
  PortalAccountProfileRoute: typeof PortalAccountProfileRoute
  PortalAccountSecurityRoute: typeof PortalAccountSecurityRoute
  PortalAccountSessionsRoute: typeof PortalAccountSessionsRoute
  PortalOrganizationsOrgIdRoute: typeof PortalOrganizationsOrgIdRouteWithChildren
  PortalAccountIndexRoute: typeof PortalAccountIndexRoute
  PortalOrganizationsIndexRoute: typeof PortalOrganizationsIndexRoute
}

const PortalRouteChildren: PortalRouteChildren = {
  PortalApplicationsRoute: PortalApplicationsRoute,
  PortalAccountConnectedRoute: PortalAccountConnectedRoute,
  PortalAccountContactsRoute: PortalAccountContactsRoute,
  PortalAccountProfileRoute: PortalAccountProfileRoute,
  PortalAccountSecurityRoute: PortalAccountSecurityRoute,
  PortalAccountSessionsRoute: PortalAccountSessionsRoute,
  PortalOrganizationsOrgIdRoute: PortalOrganizationsOrgIdRouteWithChildren,
  PortalAccountIndexRoute: PortalAccountIndexRoute,
  PortalOrganizationsIndexRoute: PortalOrganizationsIndexRoute,
}

const PortalRouteWithChildren =
  PortalRoute._addFileChildren(PortalRouteChildren)

interface ConsoleApplicationsRouteChildren {
  ConsoleApplicationsAppIdRoute: typeof ConsoleApplicationsAppIdRoute
}

const ConsoleApplicationsRouteChildren: ConsoleApplicationsRouteChildren = {
  ConsoleApplicationsAppIdRoute: ConsoleApplicationsAppIdRoute,
}

const ConsoleApplicationsRouteWithChildren =
  ConsoleApplicationsRoute._addFileChildren(ConsoleApplicationsRouteChildren)

interface ConsoleUsersRouteChildren {
  ConsoleUsersUserIdRoute: typeof ConsoleUsersUserIdRoute
}

const ConsoleUsersRouteChildren: ConsoleUsersRouteChildren = {
  ConsoleUsersUserIdRoute: ConsoleUsersUserIdRoute,
}

const ConsoleUsersRouteWithChildren = ConsoleUsersRoute._addFileChildren(
  ConsoleUsersRouteChildren,
)

interface ConsoleRouteChildren {
  ConsoleApplicationsRoute: typeof ConsoleApplicationsRouteWithChildren
  ConsoleClientsRoute: typeof ConsoleClientsRoute
  ConsoleResourcesRoute: typeof ConsoleResourcesRoute
  ConsoleRolesRoute: typeof ConsoleRolesRoute
  ConsoleSamlRoute: typeof ConsoleSamlRoute
  ConsoleUsersRoute: typeof ConsoleUsersRouteWithChildren
  ConsoleWebhooksRoute: typeof ConsoleWebhooksRoute
  ConsoleIndexRoute: typeof ConsoleIndexRoute
}

const ConsoleRouteChildren: ConsoleRouteChildren = {
  ConsoleApplicationsRoute: ConsoleApplicationsRouteWithChildren,
  ConsoleClientsRoute: ConsoleClientsRoute,
  ConsoleResourcesRoute: ConsoleResourcesRoute,
  ConsoleRolesRoute: ConsoleRolesRoute,
  ConsoleSamlRoute: ConsoleSamlRoute,
  ConsoleUsersRoute: ConsoleUsersRouteWithChildren,
  ConsoleWebhooksRoute: ConsoleWebhooksRoute,
  ConsoleIndexRoute: ConsoleIndexRoute,
}

const ConsoleRouteWithChildren =
  ConsoleRoute._addFileChildren(ConsoleRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  PortalRoute: PortalRouteWithChildren,
  ConsoleRoute: ConsoleRouteWithChildren,
  InviteTokenRoute: InviteTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
